name: Auto Merge Main to Testing Branch in server
on:
push:
  push:
    branches:
      -main
jobs:
  merge:
    runs-on:ubuntu-latest
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
      token: ${{secrets.ACTIONS_PAT}}
    -name: Configure Git
      run:  |
        git config --global user.name "venkatagopikrishna"
        git config --global user.email "gopivantla@gmail.com"
    - name: Fetch all branches
        run: git fetch --all
    - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrelated-histories
          git push origin testing